import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ArrowLeft, ArrowUpRight, Check, Shield, type LucideIcon } from 'lucide-react'
import { SiteFooter, SiteHeader } from '@/components/site-shell'
import { Reveal } from '@/components/site-interactions'

const serviceData: Record<string, { title: string; kicker: string; summary: string; icon: LucideIcon; outcomes: string[]; details: string[] }> = {
  'managed-detection-response': { title: 'Managed Detection & Response', kicker: 'See more. Sleep better.', summary: 'A dedicated team of threat hunters, analysts, and responders watching over your environment around the clock.', icon: Shield, outcomes: ['24/7 monitoring and triage', 'Human-led threat hunting', 'Containment and guided response', 'Executive-ready reporting'], details: ['Your security team gains a calm, experienced extension that knows your environment and learns its patterns.', 'We turn an ocean of alerts into a short list of decisions, with context on what happened and what to do next.'] },
  'cloud-security': { title: 'Cloud Security', kicker: 'Move fast. Stay grounded.', summary: 'Secure cloud foundations that give engineering teams room to move without widening your attack surface.', icon: Shield, outcomes: ['Cloud posture management', 'Identity and permissions review', 'Workload and container security', 'Secure architecture guidance'], details: ['Whether you are modernizing a legacy estate or launching cloud-native products, we help security become part of the build system.', 'Our team maps your real-world dependencies and creates guardrails that support delivery instead of slowing it down.'] },
  'penetration-testing': { title: 'Penetration Testing', kicker: 'Find the path first.', summary: 'Adversarial testing that shows you how a motivated attacker would get in, move around, and create impact.', icon: Shield, outcomes: ['Web and API testing', 'Cloud and infrastructure testing', 'Red team exercises', 'Actionable remediation plan'], details: ['We go beyond a checklist. Every engagement is scoped around the risks, assets, and business outcomes that matter most to you.', 'You finish with a prioritized path forward, not a report that gathers dust.'] },
  'security-compliance': { title: 'Security Compliance', kicker: 'Turn requirements into resilience.', summary: 'Practical compliance programs that make trust easier to earn and security easier to operate.', icon: Shield, outcomes: ['SOC 2 and ISO 27001 readiness', 'Control design and mapping', 'Evidence automation strategy', 'Audit preparation and support'], details: ['Compliance is a floor, not the ceiling. We translate frameworks into habits and controls your team can keep after the audit ends.', 'Our advisors help you answer the hard questions without losing sight of your customers or your roadmap.'] },
  'incident-response': { title: 'Incident Response', kicker: 'Calm in the critical hour.', summary: 'Experienced response when the unexpected happens, from first signal to full recovery and lessons learned.', icon: Shield, outcomes: ['24/7 emergency support', 'Investigation and containment', 'Crisis communications guidance', 'Recovery and post-incident review'], details: ['The first decisions after an incident shape the entire outcome. Our responders bring structure, clarity, and an unflappable point of view.', 'After the fire is out, we help turn the experience into stronger controls and better readiness.'] },
  'identity-access-management': { title: 'Identity & Access Management', kicker: 'Make access intentional.', summary: 'A modern identity strategy that puts the right access in the right hands, at the right time.', icon: Shield, outcomes: ['Identity strategy and architecture', 'Privileged access management', 'Zero trust foundations', 'Lifecycle automation'], details: ['Identity is your most important security boundary. We help you design access around how your people and systems really work.', 'The result is less friction for the right users and far less room for the wrong ones.'] },
}

const serviceList = Object.keys(serviceData).map((slug) => ({ slug, label: serviceData[slug].title }))

export function generateStaticParams() { return serviceList.map(({ slug }) => ({ slug })) }

export default async function ServicePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const service = serviceData[slug]
  if (!service) notFound()
  const Icon = service.icon
  return <main><SiteHeader /><section className="service-hero"><div className="service-hero-pattern" aria-hidden="true" /><div className="container service-hero-content"><Link href="/#services" className="back-link"><ArrowLeft size={15} /> All capabilities</Link><Reveal><div className="service-page-icon"><Icon size={28} /></div><p className="eyebrow eyebrow-light">{service.kicker}</p><h1>{service.title}</h1><p className="service-summary">{service.summary}</p><Link href="/#contact" className="button button-bright">Talk to an expert <ArrowUpRight size={17} /></Link></Reveal></div></section><section className="section"><div className="container detail-grid"><Reveal><p className="eyebrow">How we help</p><h2>Clarity when<br /><span>it counts.</span></h2></Reveal><Reveal className="detail-copy"><p>{service.details[0]}</p><p>{service.details[1]}</p><div className="outcome-list">{service.outcomes.map((outcome) => <div key={outcome}><Check size={17} /><span>{outcome}</span></div>)}</div></Reveal></div></section><section className="section section-pale"><div className="container"><div className="section-heading centered-heading"><p className="eyebrow">More ways to protect what matters</p><h2>Explore the full<br /><span>Aegis North stack.</span></h2></div><div className="related-links">{serviceList.filter((item) => item.slug !== slug).slice(0, 3).map((item) => <Link key={item.slug} href={`/services/${item.slug}`} className="related-link"><span>{item.label}</span><ArrowUpRight size={18} /></Link>)}</div></div></section><SiteFooter /></main>
}
